---
name: "ci"

on:
    pull_request: {}
    push:
        branches:
            - "master"

env:
    CI: true

jobs:
    run:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@v1"

            - name: "Set up Node.js"
              uses: "actions/setup-node@v1"
              with:
                  node-version: "14.15"

            - name: "Install"
              run: "yarn install --no-audit"

            - name: "Lint"
              run: "./bin/lint"
